name: Sync packages

on:
  pull_request:
    branches: '**'
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday.

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Sync packages
        run: cd apps/svelte.dev && pnpm sync-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: '(AUTO) Update packages data'
          title: '🤖 Update packages data'
          body: Automatically fetch latest packages data from NPM & GitHub.
          base: main
          branch: ci/update-packages-data
          delete-branch: true
